# Generated by Django 4.2.6 on 2024-02-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
